### PR TITLE
fix hardware identity oid check logic.

### LINKED ISSUE #14: The extension check logic is not correct.
Currently, the code assumes the extension data passed in is as

```
extnID      OBJECT IDENTIFIER,
critical    BOOLEAN DEFAULT FALSE,
extnValue   OCTET STRING
            -- contains the DER encoding of an ASN.1 value
            -- corresponding to the extension type identified
            -- by extnID
```

while the actual extension data passed in is `Extensions`, showed as 
```
Extensions  ::=  SEQUENCE SIZE (1..MAX) OF Extension

Extension  ::=  SEQUENCE  {
    extnID      OBJECT IDENTIFIER,
    critical    BOOLEAN DEFAULT FALSE,
    extnValue   OCTET STRING
                -- contains the DER encoding of an ASN.1 value
                -- corresponding to the extension type identified
                -- by extnID
        }
```

https://github.com/ccc-spdm-tools/spdm-rs/blob/cb06559c33c27231bad686e9a854ffc97710b50a/spdmlib/src/crypto/x509v3.rs#L446-L468

### PR DESCRIPTION
**Pull request by longlongyang**
fix #14

### CODE REVIEW

File: spdmlib/src/crypto/x509v3.rs [hunk 1]
```diff
@@ -470,6 +470,60 @@ fn find_target_object_identifiers(data: &[u8], target_oid: &[u8]) -> SpdmResult<
     Ok(target_oid_find_success)
 }
 
+// IN  (extension sequences slice, target oid)
+// OUT true when find target oid
+// OUT false when not find target oid
+fn find_target_object_identifiers_in_extensions(
```
Comment (OuyangHang33) [inline spdmlib/src/crypto/x509v3.rs:476]: `find_target_object_identifiers` can enter sequence slice or extnValue to find the target oid, so It's fine to keep using `find_target_object_identifiers` to search hardware oid, no need additional function to do the search work.

https://github.com/ccc-spdm-tools/spdm-rs/blob/cb06559c33c27231bad686e9a854ffc97710b50a/spdmlib/src/crypto/x509v3.rs#L461-L463

File: spdmlib/src/crypto/x509v3.rs [hunk 2]
```diff
@@ -1223,7 +1283,7 @@ mod tests {
         assert!(check_leaf_certificate(&end1, true).is_ok());
         assert!(check_leaf_certificate(&end1, false).is_ok());
         assert!(check_leaf_certificate(&end2, false).is_ok());
-        assert!(check_leaf_certificate(&end2, true).is_err());
+        assert!(check_leaf_certificate(&end2, true).is_ok());
```
Comment (OuyangHang33) [inline spdmlib/src/crypto/x509v3.rs:1286]: end2 contains hardware oid and alias cert shall not have hardware oid. Need return Err.

**Comment by longlongyang** [comment]
As synced offline, we both agreed that:
1. use another function to handle a whole extensions (sequence of extension).
2. test case is designed well, no need to change the test case.

File: spdmlib/src/crypto/x509v3.rs [hunk 3]
```diff
@@ -692,13 +862,11 @@ pub fn check_leaf_certificate(cert: &[u8], is_alias_cert_model: bool) -> SpdmRes
...
 
-    if is_alias_cert_model
-        && find_target_object_identifiers(extension_data, OID_DMTF_SPDM_HARDWARE_IDENTITY)?
-    {
+    if is_alias_cert_model && find_hardware_object_identifiers_in_extensions(extension_data)? {
         info!("Hardware identity OID shall not be present in alias cert!\n");
         Err(SPDM_STATUS_VERIF_FAIL)
     } else if !is_alias_cert_model
-        && !find_target_object_identifiers(extension_data, OID_DMTF_SPDM_HARDWARE_IDENTITY)?
+        && !find_hardware_object_identifiers_in_extensions(extension_data)?
```
Comment (jyao1) [inline spdmlib/src/crypto/x509v3.rs:869]: Why we change a generic function to a specific function?

Comment (longlongyang) [reply spdmlib/src/crypto/x509v3.rs:869]: > Why we change a generic function to a specific function?

Because, it is confusing for a generic function to find a target oid. RFC 5280 says
```
Extension  ::=  SEQUENCE  {
    extnID      OBJECT IDENTIFIER,
    critical    BOOLEAN DEFAULT FALSE,
    extnValue   OCTET STRING
                -- contains the DER encoding of an ASN.1 value
                -- corresponding to the extension type identified
                -- by extnID
        }
```
to find a target oid in extnValue need the context of extension type. So it is better to add some specific items in function name to indicate the context of extension type. In this PR, hardware_object_identifiers indicates this function works under SPDM context, to find a
```
id-DMTF-hardware-identity id-spdm-cert-oid :: = {
    spdmOID { id-DMTF-spdm 2 }
    spdmOIDdefinition ABSENT
}

```
it should be more precise.
